name: run Api Tests
on:
  push:
    branches: [main]


  job:
    test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - uses: actions/setup-Java@v3
        with:
          java-version: '21'
          cache : 'maven'
      - name: Test Results
        run: mvn clean test



